# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mazo_de_cartas', models.TextField(default=b"{u'cartas': {'c36': None, 'c40': None, 'c37': None, 'c47': None, 'c41': None, 'c19': None, 'c18': None, 'c39': None, 'c38': None, 'c13': None, 'c12': None, 'c11': None, 'c10': None, 'c17': None, 'c16': None, 'c15': None, 'c14': None, 'c44': None, 'c42': None, 'c45': None, 'c46': None, 'c35': None, 'c9': None, 'c8': None, 'c34': None, 'c3': None, 'c2': None, 'c1': None, 'c0': None, 'c7': None, 'c6': None, 'c5': None, 'c4': None, 'c22': None, 'c23': None, 'c20': None, 'c21': None, 'c26': None, 'c27': None, 'c24': None, 'c25': None, 'c31': None, 'c28': None, 'c29': None, 'c48': None, 'c49': None, 'c30': None, 'c33': None, 'c43': None, 'c32': None}, u'nombre': None, u'utilizable': False, u'id': None}")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
