# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oro',
            field=models.IntegerField(default=875),
        ),
    ]
