# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userprofile_oro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=850)),
                ('decks', models.TextField(default=b"{u'deck_4': {}, u'deck_5': {}, u'deck_6': {}, u'deck_7': {}, u'deck_0': {}, u'deck_1': {}, u'deck_2': {}, u'deck_3': {}, u'deck_8': {}, u'deck_9': {}}")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
