# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160104_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='clp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icons',
            field=models.ManyToManyField(null=True, to='shop.Icon'),
        ),
    ]
