# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151229_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserprofile',
            name='decks',
            field=models.TextField(default=b"{u'deck_4': {}, u'deck_5': {}, u'deck_6': {}, u'deck_7': {}, u'deck_1': {}, u'deck_2': {}, u'deck_3': {}, u'deck_8': {}, u'deck_9': {}, u'deck_10': {}}"),
        ),
    ]
