# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20151229_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserprofile',
            name='decks',
            field=models.TextField(default=b"{u'deck_4': {u'is_created': False, u'description': None, u'id': 4, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_1': {u'is_created': False, u'description': None, u'id': 1, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_2': {u'is_created': False, u'description': None, u'id': 2, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_3': {u'is_created': False, u'description': None, u'id': 3, u'cards': {}, u'is_complete': False, u'name': None}}"),
        ),
    ]
