# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20151229_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserprofile',
            name='decks',
            field=models.TextField(default=b"{u'deck_4': {u'is_created': False, u'description': None, u'id': 4, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_5': {u'is_created': False, u'description': None, u'id': 5, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_6': {u'is_created': False, u'description': None, u'id': 6, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_7': {u'is_created': False, u'description': None, u'id': 7, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_1': {u'is_created': False, u'description': None, u'id': 1, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_2': {u'is_created': False, u'description': None, u'id': 2, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_3': {u'is_created': False, u'description': None, u'id': 3, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_8': {u'is_created': False, u'description': None, u'id': 8, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_9': {u'is_created': False, u'description': None, u'id': 9, u'cards': {}, u'is_complete': False, u'name': None}, u'deck_10': {u'is_created': False, u'description': None, u'id': 10, u'cards': {}, u'is_complete': False, u'name': None}}"),
        ),
    ]
