# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20151229_0831'),
        ('core', '0009_auto_20151229_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduserprofile',
            name='icons',
            field=models.ManyToManyField(to='shop.Icon', verbose_name='Iconos'),
        ),
    ]
