# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_extendeduserprofile_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserprofile',
            name='icons',
            field=models.ManyToManyField(to='shop.Icon'),
        ),
    ]
