# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20151229_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='file_path',
            field=models.FilePathField(path='/static/img/icons'),
        ),
    ]
