# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20151229_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='url',
        ),
        migrations.AddField(
            model_name='icon',
            name='path',
            field=models.CharField(default='/static/img/icons/default.png', max_length=64),
        ),
    ]
