# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_icon_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
