# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_icon_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='available',
            new_name='enabled',
        ),
    ]
