# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20151230_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='cost',
        ),
        migrations.AddField(
            model_name='icon',
            name='price',
            field=models.IntegerField(default=1000000),
        ),
    ]
