# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20160103_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='price',
            field=models.IntegerField(default=1750),
        ),
    ]
