# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('numero_de_coleccionista', models.CharField(max_length=16)),
                ('slug', models.SlugField(editable=False, max_length=16)),
            ],
        ),
    ]
